---
- name: Ensure the data directory is created
  file:
    path: /data
    state: directory
  become: yes

- name: Ensure the data volume is formatted
  filesystem:
    fstype: ext4
    dev: /dev/nvme0n1
  become: yes

- name: Mount the data volume to the data directory
  mount:
    path: /data
    src: /dev/nvme0n1
    fstype: ext4
    state: mounted
  become: yes

- name: Run cocalc docker image
  docker_container:
    name: cocalc
    image: sagemathinc/cocalc:latest
    memory: 3G
    cpu_period: 100000
    cpu_quota: 150000
    volumes:
      - /data/cocalc:/projects
    ports:
      - 443:443
  become: yes
