---
- name: "Add Docker GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker

- name: "Install misc packages"
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - aptitude
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: "Install docker"
  apt:
    name: "docker-ce"
    update_cache: yes
